#!/usr/bin/env bash
#  Double the number of webservers

apt-get update
apt-get -y install nginx
service nginx start
sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
service nginx restart
