#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
sudo apt-get install -y haproxy=1.8.\*

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 519443-web-01 54.210.88.19:80 check
   server 519443-web-02 54.157.134.108:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" > /etc/default/haproxy

sudo service haproxy start
