#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

apt-get -y update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" | sudo tree -a /etc/default/haproxy
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 519443-web-01 18.210.13.116:80 check
   server 519443-web-02 54.157.134.108:80 check
" | sudo tree -a /etc/haproxy/haproxy.cfg

service haproxy start
