#!/usr/bin/env bash
# pings an IP address passed as an argument

# ip
IP="${1}"

# filename
#fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
