#!/usr/bin/env bash
# Make it sweet and short

#ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#service nginx restart
#rm /run/nginx.pid
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill -o nginx

