#!/usr/bin/env bash
# uses ssh to connect to your server using the private key
# ~/.ssh/school with the user ubuntu

#server_ip = "100.26.120.73"
#private_key = "~/.ssh/school"
#user = "ubuntu"
# Connect to Server
ssh -i ~/.ssh/school ubuntu@100.26.120.73
